# Generated by Django 3.1.4 on 2020-12-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warranty_Details', '0002_auto_20201230_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warranty_details',
            name='Importance',
        ),
        migrations.AddField(
            model_name='warranty_details',
            name='compensation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='warranty_details',
            name='importance',
            field=models.CharField(choices=[('Critical', 'Aa'), ('Urgent', 'Bb'), ('Moderate', 'Cc'), ('Minor', 'Dd')], default='Minor', max_length=8),
        ),
        migrations.AddField(
            model_name='warranty_details',
            name='internal_report',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='warranty_details',
            name='remark',
            field=models.CharField(choices=[('Wating Maker Reply', 'Wmr'), ('Wating Yard Reply', 'Wyr'), ('Wating Vessel Reply', 'Wvr'), ('Item Ready', 'Itr')], default='Wating Maker Reply', max_length=20),
        ),
        migrations.AddField(
            model_name='warranty_details',
            name='report_summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='warranty_details',
            name='requested_action',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='warranty_details',
            name='return_product',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='warranty_details',
            name='unit',
            field=models.CharField(blank=True, choices=[('1', 'Usd'), ('2', 'Cad'), ('3', 'Eur'), ('4', 'Krw')], max_length=3, null=True),
        ),
    ]
