# Generated by Django 3.1.4 on 2020-12-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warranty_Details', '0003_auto_20201231_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty_details',
            name='report_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warranty_details',
            name='requested_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
