# Generated by Django 3.1.2 on 2020-10-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
