# Generated by Django 3.1.2 on 2020-11-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hulls', '0003_auto_20201102_1214'),
        ('owners', '0002_auto_20201014_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='owner',
            name='hulls',
            field=models.ManyToManyField(related_name='hulls', to='hulls.Hull'),
        ),
    ]
