# Generated by Django 3.1.2 on 2020-11-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_auto_20201102_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='hulls',
        ),
    ]
