# Generated by Django 3.1.4 on 2021-01-02 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hull_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='relevant_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('item', models.CharField(blank=True, max_length=50)),
                ('report_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hull_report.hull_report')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
