# Generated by Django 3.1.4 on 2020-12-20 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hulls', '0003_auto_20201102_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hull_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('report_number', models.IntegerField()),
                ('subject', models.CharField(max_length=120)),
                ('equipment', models.CharField(max_length=120)),
                ('manufacturer', models.CharField(max_length=120)),
                ('drawing_number', models.CharField(max_length=120)),
                ('type_name', models.CharField(max_length=120)),
                ('description_damage', models.TextField()),
                ('occurrence_date', models.DateField()),
                ('putative_cause', models.CharField(max_length=120)),
                ('vessel_comment', models.TextField()),
                ('hulls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hulls.hull')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
