# Generated by Django 3.1.4 on 2021-01-02 04:11

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturers',
            name='product',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='company_registry',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
