# Generated by Django 3.1.2 on 2020-11-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hulls', '0002_auto_20201014_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hull',
            options={'ordering': ['-pk']},
        ),
        migrations.RenameField(
            model_name='hull',
            old_name='owner',
            new_name='owners',
        ),
    ]
